#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 31 22:08:06 EDT 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tmp_open_list_queue_tb_behav -key {Behavioral:sim_2:Functional:tmp_open_list_queue_tb} -tclbatch tmp_open_list_queue_tb.tcl -view /home/charlielinux/Workspace/hwpq_qw2246/systolic_array/vivado_systolic_array/tmp_open_list_queue_tb_behav.wcfg -log simulate.log"
xsim tmp_open_list_queue_tb_behav -key {Behavioral:sim_2:Functional:tmp_open_list_queue_tb} -tclbatch tmp_open_list_queue_tb.tcl -view /home/charlielinux/Workspace/hwpq_qw2246/systolic_array/vivado_systolic_array/tmp_open_list_queue_tb_behav.wcfg -log simulate.log

