#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 25 00:50:01 EDT 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim register_tree_tb_behav -key {Behavioral:sim_1:Functional:register_tree_tb} -tclbatch register_tree_tb.tcl -view /home/charlie/Workspace/pq_research/hwpq_qw2246/register_tree/vivado_register_tree/register_tree_tb_behav.wcfg -log simulate.log"
xsim register_tree_tb_behav -key {Behavioral:sim_1:Functional:register_tree_tb} -tclbatch register_tree_tb.tcl -view /home/charlie/Workspace/pq_research/hwpq_qw2246/register_tree/vivado_register_tree/register_tree_tb_behav.wcfg -log simulate.log

